[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
"SimSessionRX600" 
[CONFIGURATIONS]
"Config1" 
"Debug" 
"Release" 
"SimDebug_RX600" 
[CURRENT_CONFIGURATION]
"Config1" 
[CURRENT_SESSION]
"DefaultSession" 
[GENERAL_DATA_PROJECT]
[GENERAL_DATA_CONFIGURATION_Config1]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Config1]
"DefaultSession" 
"SimSessionRX600" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Debug]
"DefaultSession" 
"SimSessionRX600" 
[GENERAL_DATA_CONFIGURATION_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Release]
"DefaultSession" 
"SimSessionRX600" 
[GENERAL_DATA_CONFIGURATION_SimDebug_RX600]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_SimDebug_RX600]
"DefaultSession" 
"SimSessionRX600" 
[GENERAL_DATA_CONFIGURATION_SESSION_Config1_SimSessionRX600]
[GENERAL_DATA_SESSION_SimSessionRX600]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_SimSessionRX600]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_SimDebug_RX600_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_SimSessionRX600]
[GENERAL_DATA_CONFIGURATION_SESSION_Config1_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_SimDebug_RX600_SimSessionRX600]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_DefaultSession]
[END]
