;------------------------------------------------------------------------
;                                                                       |
;   FILE        :lowlvl.src                                             |
;   DATE        :Fri, Aug 29, 2014                                      |
;   DESCRIPTION :Program of Low level                                   |
;   CPU TYPE    :RX62N                                                  |
;                                                                       |
;   This file is generated by Renesas Project Generator (Ver.4.53).     |
;   NOTE:THIS IS A TYPICAL EXAMPLE.                                     |
;                                                                       |
;------------------------------------------------------------------------
                  

         .GLB    _charput
         .GLB    _charget
		 .GLB	_putchar

		 .GLB	_stack
		 .GLB	_vectors
		 .GLB	_datastart
		 .GLB	_romdatastart
		 .GLB	_romdatacopysize
		 .GLB	_bssstart
		 .GLB	_bsssize
		 .GLB	etext


SIM_IO   .EQU 0h
#define SIM_IO	0

         .SECTION   P,CODE
;-----------------------------------------------------------------------
;  _charput:
;-----------------------------------------------------------------------

_putchar:
_charput:
         MOV.L      #IO_BUF,R2
         MOV.B      R1,[R2]
         MOV.L      #1220000h,R1
         MOV.L      #PARM,R3
         MOV.L      R2,[R3]
         MOV.L      R3,R2
         MOV.L      #0,R3		; SIM_IO
         JSR        R3
         RTS


_stack:
_vectors:
_datastart:
_romdatastart:
_romdatacopysize:
_bssstart:
_bsssize:
etext:



;-----------------------------------------------------------------------
;  _charget:
;-----------------------------------------------------------------------  
_charget:
        MOV.L       #1210000h,R1
        MOV.L       #IO_BUF,R2
        MOV.L       #PARM,R3
        MOV.L       R2,[R3]
        MOV.L       R3,R2
        MOV.L       #0,R3			; SIM_IO
        JSR         R3
        MOV.L       #IO_BUF,R2
        MOVU.B      [R2],R1
        RTS

		.glb	_open
		.glb	_read
		.glb	_lseek
		.glb	_isatty
		.glb	_fstat
		.glb	_close

_open:
_read:
_lseek:
_isatty:
_fstat:
_close:
		MOV.L	#0,R1
		RTS

;-----------------------------------------------------------------------
;  I/O Buffer
;-----------------------------------------------------------------------
         .SECTION  B,DATA,ALIGN=4
PARM:    .BLKL     1
         .SECTION  B_1,DATA
IO_BUF:  .BLKB     1
         .END
