/*------------------------------------------------------------------------
                                                                       |
   FILE        : reset_program.asm                                     |
   DATE        :  Mon, Jun 29, 2015                                    |
   DESCRIPTION :   Reset Program                                       |
   CPU TYPE    :    RX63N                                              |
                                                                       |
   This file is generated by KPIT GNU Project Generator (Ver.4.5).     |
                                                                       |
------------------------------------------------------------------------*/
                       
                                                                           
                                                                           
                                                                           
                                                                           
                                                                           
                                                                           
                                                                           
                                                                          
                                                                           
                                                                           
                                                                         
	/*reset_program.asm*/

	.list
	.section .text
/* call to exit*/
_exit:
    
	.text	
	.end
